config/routes.rb
Rails.application.routes.draw do
  resources :mini_requests, only: :create
  resources :feedbacks, only: :create
  resources :lists
  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
  get "/robots.:format", to: "errors#robots"

  devise_for :users, controllers: { confirmations: 'confirmations', invitations: 'users/invitations', registrations: 'users/registrations', sessions: 'users/sessions' }

  authenticate :user, -> (user) { user.admin? } do
    mount PgHero::Engine, at: "pghero"
  end

  resources :after_signup, path: "/welcome"
  resources :suggested_keywords, only: [:create, :destroy]
  resources :suggested_communities, only: [:create, :destroy]

  resources :groups, only: [:show], path: "/l"

  root to: 'home#all'
  get '/search/solutions', to: 'search#solutions'

  get 'home', to: 'home#home'
  get 'recent', to: 'home#recent'
  # get 'requests', to: 'home#requests'
  # get 'requests/recent', to: 'home#requests_recent'
  get 'all', to: 'home#all'
  # get '/search/requests', to: 'search#requests'

  resources :industries, only: [], type: "Industry", path: "/i" do
    get "/", to: "solutions#niche_index"
    # get "/requests", to: "requests#niche_index"
    get "/search", to: "search#niche_index"
    member do
      get 'follow'
      get 'unfollow'
    end
  end

  resources :occupations, only: [], type: "Occupation", path: "/o" do
    get "/", to: "solutions#niche_index"
    # get "/requests", to: "requests#niche_index"
    get "/search", to: "search#niche_index"
    member do
      get 'follow'
      get 'unfollow'
    end
  end

  resources :products, only: [:index, :show]

  # Force www redirect
  # Start server with rails s -p 3000 -b lvh.me
  # Then go to http://www.lvh.me:3000
  # constraints(host: /^(?!www\.)/i) do
  #   get "controller#action" => redirect { |params, request|
  #     URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
  #   }
  # end

  post 'solutions/new', to: 'solutions#create'
  resources :solutions, except: [:index] do
    member do
      get 'follow'
      get 'unfollow'
      get 'upvote'
      get 'remove_upvote'
      resources :comments, except: :new do
        member do
          get 'upvote'
          get 'remove_upvote'
          delete 'really_destroy'
          post 'restore'
        end
      end
    end
  end

  post 'requests/new', to: 'requests#create'
  resources :requests do
    member do
      get 'upvote'
      get 'remove_upvote'
      get 'follow'
      get 'unfollow'
      resources :comments, except: :new do
        member do
          get 'upvote'
          get 'remove_upvote'
          delete 'really_destroy'
          post 'restore'
        end
      end
    end
  end
  resources :industry_categories, path: '/explore/i'
  resources :occupation_categories, path: '/explore/o'


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # before_action :set_meta
  skip_after_action :verify_authorized

  def communities
    if user_signed_in?
      redirect_to controller: :home, action: :home
    end
  end

  def solutions
    gon.index_name = 'solutions'
    set_meta_tags title: "solved: Find new and better solutions to your problems from people like you.",
                  description: "solved is a community of problem solvers and makers helping you find (or build!) better solutions to problems you face. Learn about new ways of doing things in your industry or occupation from people like you all around the world. Give back to the community by sharing your experience with products you love. Connect with budding entrepreneurs and give them feedback on their products to help them build better products for you.",
                  site: nil,
                  canonical: search_solutions_url
  end

  private

  # def set_meta
  #   set_meta_tags title: "solved: Find new and better solutions to your problems from people like you.",
  #                 description: "solved is a community of problem solvers and makers helping you find (or build!) better solutions to problems you face. Learn about new ways of doing things in your industry or occupation from people like you all around the world. Give back to the community by sharing your experience with products you love. Connect with budding entrepreneurs and give them feedback on their products to help them build better products for you.",
  #                 site: nil,
  #                 canonical: root_url

  # end


end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_header.html.haml
%div{class: "bg-transparent top-0 z-40"}
  %div{class: "flex justify-center border-0 px-4 md:px-0"}
    %div{data: { controller: "toggle"},
        class: "max-w-screen-lg w-full flex items-center justify-between py-2"}
      %div{class: "flex items-end"}
        %div{class: "fill-current h-8 w-28"}
          = link_to root_path do
            - if current_page?(root_url)
              %h1= svg_tag 'logo', alt: "solved"
            - else
              = svg_tag 'logo', alt: "solved"
        %div{class: "leading ml-2 font-source font-bold text-black block flex flex-col items-start"}
          %div{class: ""}
            Beta


      %nav{class: "hidden md:flex items-center"}
        %div{class: "flex items-center space-x-2 pr-4 border-r border-gray-400"}
          -# %a(data-feedback-fish){href: "#", class: "p-1.5 text-yellow-500 rounded border border-transparent hover:bg-gray-200 hover:border-gray-400", data: { turbolinks: false }, "data-feedback-fish-userid": "#{user_signed_in? ? current_user.email : nil}"}
          -#   <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" viewBox="0 0 20 20" fill="currentColor">
          -#   <path d="M11 3a1 1 0 10-2 0v1a1 1 0 102 0V3zM15.657 5.757a1 1 0 00-1.414-1.414l-.707.707a1 1 0 001.414 1.414l.707-.707zM18 10a1 1 0 01-1 1h-1a1 1 0 110-2h1a1 1 0 011 1zM5.05 6.464A1 1 0 106.464 5.05l-.707-.707a1 1 0 00-1.414 1.414l.707.707zM5 10a1 1 0 01-1 1H3a1 1 0 110-2h1a1 1 0 011 1zM8 16v-1h4v1a2 2 0 11-4 0zM12 14c.015-.34.208-.646.477-.859a4 4 0 10-4.954 0c.27.213.462.519.476.859h4.002z" />
          -#   </svg>
          -# - if params[:controller] == "search"
          -#   %div{class: "flex-shrink-0 relative text-gray-900", "data-controller": "dropdown", "data-dropdown-active-class": "bg-gray-200 border-gray-400", "data-dropdown-active-target": '#activeTarget'}
          -#     %div{"data-action": "mouseover->dropdown#show mouseout->dropdown#hide click->dropdown#toggle click@window->dropdown#hide", role: "button", class: "flex-shrink-0  inline-block select-none"}
          -#       %span{id: "activeTarget", class: "flex-shrink-0 text-sm leading-none px-2 py-2  block rounded font-semibold border border-transparent"}
          -#         My Communities

          -#     %div{"data-dropdown-target": "menu", class: "absolute right-0 hidden mt-2.5 w-56 z-40"}
          -#       %div{class: "overflow-y-auto max-h-72 w-full bg-white border rounded shadow divide-y divide-gray-300"}
          -#         - if user_signed_in?
          -#           - if current_user.niche_list.present?
          -#             - current_user.niche_list.each do |n|
          -#               = link_to n.title,  n, class: 'text-sm transition-all  block px-3 py-3 text-gray-900 bg-white hover:bg-secondary hover:text-white whitespace-no-wrap'
          -#           - else
          -#             %div{class: 'text-sm block px-3 py-3 text-gray-900 bg-white whitespace-no-wrap'}
          -#               Follow a community to view it here
          -#         - else
          -#           = link_to "Log In to save a community", new_user_session_path, class: 'text-sm two-lines-only block px-3 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-no-wrap'

          -# - else

          -# %div{class: "relative text-gray-900", "data-controller": "dropdown", "data-dropdown-active-class": "bg-gray-200 border-gray-400", "data-dropdown-active-target": '#activeTarget2'}
          -#   %div{"data-action": "mouseenter->dropdown#show mouseleave->dropdown#hide click->dropdown#toggle click@window->dropdown#hide", role: "button", class: "inline-block select-none"}
          -#     %span{id: "activeTarget2", class: "text-sm leading-none px-2 py-2  block rounded font-semibold border border-transparent"}
          -#       New

          -#   %div{"data-dropdown-target": "menu", class: "absolute right-0 hidden mt-2.5 w-24 z-40"}
          -#     %div{class: "overflow-hidden bg-white border rounded shadow divide-y divide-gray-300"}
          -#       = link_to "Request" , new_request_path, class: 'font-medium hover:font-semibold transition-all text-left text-sm two-lines-only block px-3 py-3 text-gray-900 bg-white hover:bg-secondary hover:text-white whitespace-no-wrap'
          -#       = link_to "Solution" , new_solution_path, class: 'font-medium hover:font-semibold transition-alltext-left text-sm two-lines-only block px-3 py-3 text-gray-900 bg-white hover:bg-secondary hover:text-white whitespace-no-wrap'
          - if !user_signed_in?
            = link_to "All" , all_path, class: "flex-shrink-0 text-sm leading-none px-2 py-2 block rounded hover:bg-gray-200 font-semibold text-gray-900 border border-transparent"
          - else
            = link_to "Home" , home_path, class: "flex-shrink-0 text-sm leading-none px-2 py-2 block rounded hover:bg-gray-200 font-semibold text-gray-900 border border-transparent"

          -# "text-sm text-center leading-none p-4  block hover:bg-gray-200 font-medium text-gray-900"
        %div{class: "flex-shrink-0 ml-4 flex items-center"}
          - if user_signed_in?

            %div{class: "relative", "data-controller": "dropdown", "data-dropdown-active-class": "border-gray-400 bg-gray-200", "data-dropdown-active-target": '#activeTarget3'}
              %div{id: "activeTarget3", "data-action": "mouseover->dropdown#show onmouseout->dropdown#hide click@window->dropdown#hide", role: "button", class: "flex select-none items-center border border-transparent  rounded px-2 py-0.5"}
                %div{class: "flex items-center inline-block text-gray-700"}
                  = image_tag current_user.thumbnail_url, class: "object-cover rounded-full w-7 h-7 ring-0.5 ring-white hover:ring-gray-400 hover:ring-opacity-70"
                %div{class: "text-sm font-medium ml-2"}
                  = current_user.name

              %div{"data-dropdown-target": "menu", class: "absolute right-0 hidden mt-2 w-full"}
                %div{class: "overflow-hidden bg-white border rounded shadow divide-y divide-gray-300 text-sm w-full"}
                  = link_to 'Profile',  edit_user_registration_path, class: 'font-medium hover:font-semibold transition-all text-left block p-3 text-gray-900 bg-white hover:bg-secondary hover:text-white whitespace-no-wrap'
                  = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'font-medium hover:font-semibold transition-all text-left no-underline block p-3 text-gray-900 bg-white hover:bg-secondary hover:text-white whitespace-no-wrap'
          - else
            %div{class: "space-x-2"}
              = link_to "Log In", new_user_session_path, class: "text-gray-900 font-semibold py-2 px-2 hover:bg-gray-200 rounded"
              = link_to "Sign Up", new_user_registration_path, class: "rounded font-semibold text-white py-2 px-2 bg-secondary hover:bg-opacity-90"

app/views/search/communities.html.haml
:javascript
  analytics.page('Search Communities');

%div{class: "flex justify-center pb-10"}
  %div{class: "max-w-screen-lg w-full flex flex-col items-center overflow-hidden", "data-controller": 'toggle'}
    :css
      .ais-SearchBox-input {
        @apply rounded-full bg-white;
      }
      .ais-SearchBox-reset {
        visibility: hidden;
      }
    %div{class: "w-1/2 flex flex-col mt-10"}
      #searchbox_communities

    %div{id: "app_body", class: "w-full flex flex-col items-center"}
      %div{class: "mt-8 bg-white w-1/2 rounded border border-gray-400 p-4 mb-4 #{cookies[:closeInfo] ? 'hiddn' : nil}", "data-toggle-target": 'toggleable'}
        %div{class: "text-xl flex items-center w-full justify-between font-medium"}
          Hello! 👋
          -# %div{class: "w-4 h-4  text-gray-600 hover:text-black cursor-pointer", "data-action": 'click->toggle#toggle touch->toggle#toggle', onclick: "document.cookie = setCookie('closeInfo', true, 10);"}
          -#   <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          -#   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          -#   </svg>
        %div{class: "py-1 w-full rounded-lg mt-1 text-xl"}
          Welcome to solved, a place to share and find the best new solutions to your problems.
          <br/><br/>
          🔍 Find your industry / occupation and learn about how others in your field are applying new software products to solve problems in new ways.
          -# 🔍 Search to find your industry / occupation community and learn about new ways of doing things from problem solvers and makers around the world.
          -#  that could help you earn, or help you save time and money.
          <br/><br/>
          🤫 solved is currently in beta so posting solutions and requests is limited to certain communities.
          <br/>
          %div{class: "text-sm"}
            (Posting is allowed once a community has 40 followers. Follow your community to get it unlocked!)

    #results{class: "w-full flex justify-center"}
      %div{class: "mt-10 flex flex-wrap justify-center pb-20 px-4 w-full"}
        %div{class: "max-w-screen-lg w-full flex flex-col"}
          %div{class: "font-m text-2xl"}
            Choose your industry or occupation below 👇
          %div{class: "text-lg"}
            = "(or #{link_to "explore", industry_categories_path, class: "user-link px-0.5", target: "_blank"} if you're unable to find your community)".html_safe
            #hits{class: "mt-6 mb-10 w-full"}

app/views/search/home.html.haml
:javascript
  function setCookie(cname, cvalue, exdays) {
    var d = new Date();
    d.setTime(d.getTime() + (exdays*24*60*60*1000));
    var expires = "expires="+ d.toUTCString();
    document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    console.log(cname + "=" + cvalue + ";" + expires + ";path=/");
  }

%div{class: "mt-10 flex justify-center pb-10"}
  %div{class: "max-w-screen-lg flex overflow-hidden", "data-controller": 'toggle'}
    %div{class: "w-2/3 pr-12"}
      %div{class: "bg-white w-full rounded border border-gray-400 p-4 mb-4 #{cookies[:closeInfo] ? 'hidden' : nil}", "data-toggle-target": 'toggleable'}
        %div{class: "text-xl flex items-center w-full justify-between font-medium"}
          Hello! 👋
          %div{class: "w-4 h-4  text-gray-600 hover:text-black cursor-pointer", "data-action": 'click->toggle#toggle touch->toggle#toggle', onclick: "document.cookie = setCookie('closeInfo', true, 10);"}
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
            -# <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            -# <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
            -# </svg>
        -# = "About #{niche_type}"
        %div{class: "py-1 w-full rounded-lg mt-1 text-xl"}
          Welcome to solved, a place to share and find the best new solutions to your problems.
          <br/><br/>
          🔍 Find your industry / occupation community and learn about new ways of doing things that could help you earn, or help you save time and money.
          -# Find your industry / occupation community and learn how people like you use products they love to solve their problems.
          -# Welcome to solved, a place for you to share and find the best new solutions to your problems.
          -# <br/><br/>
          -# ✨ Stay up to date by following your community to recieve a weekly email with the top solutions and requests of the week.
          -# <br/><br/>
          -# ❤️ Take part in your community and help others by posting about how you use the products you love to solve your problems.
          -#  you solve your problems with the products you love.

      - active   = "text-secondary bg-gray-fb bg-opacity-50 px-2 py-2 font-medium rounded"
      - inactive = "text-gray-900 px-2 py-2 font-medium rounded hover:bg-gray-fb hover:bg-opacity-50"
      -# - active = "px-2 py-2 rounded bg-secondary text-white font-medium"
      -# - inactive = "px-2 py-2 rounded hover:bg-secondary hover:text-white font-medium text-gray-900"
      %nav{class: "bg-white border border-gray-400 rounded px-3 py-3 space-x-2 flex justify-between"}
        - if current_page?(controller: 'search', action: 'home') || current_page?(controller: 'search', action: 'recent')
          %div
            = link_to 'Solutions', root_path, class: "#{active}"
            = link_to 'Requests', requests_path, class: "#{inactive}"
          %div
            - unless params[:tag]
              = link_to_unless_current("Top", root_path, class: "#{inactive}") do link_to 'Top', root_path, class: "#{active}" end
              = link_to_unless_current("Most Recent", [:recent], class: "#{inactive}") do link_to 'Most Recent', [:recent], class: "#{active}" end
        - else
          %div
            = link_to 'Solutions', root_path, class: "#{inactive}"
            = link_to 'Requests', requests_path, class: "#{active}"
          %div
            = link_to_unless_current("Top", [:requests], class: "#{inactive}") do link_to 'Top', [:requests], class: "#{active}" end
            = link_to_unless_current("Most Recent", [:requests, :recent], class: "#{inactive}") do link_to 'Most Recent', [:requests, :recent], class: "#{active}" end

      - if current_page?(controller: 'search', action: 'home') || current_page?(controller: 'search', action: 'recent')
        %div{class: "flex items-center mt-4 #{params[:tag].present? ? "text-base" : "text-xs"}"}
          %div{class: "font-semibold pb-4 flex-shrink-0"}
            Tags:
          - if params[:tag]
            %div{class: "flex-shrink-0 text-black mr-1 ml-3 pb-4 font-medium"}
              = params[:tag]
          %div{class: "ml-3 space-x-4 overflow-x-scroll flex items-center pb-4"}
            - Solution.general_tag_counts.each do |tag|
              - if params[:tag] != tag.name
                = link_to root_path(tag: tag.name), class: "flex-shrink-0 " do
                  %div{class: "text-gray-600 hover:text-black"}
                    = tag.name
              -# = link_to c do
              -#     %div{class: "-m-1.5 p-1.5 hover:bg-gray-200"}
              -#       = "#{c.title} (#{c.class.to_s})"
              -# = link_to_unless_current(tag.name, root_path(tag: tag.name), class: "flex-shrink-0 text-gray-600 hover:text-black") do end
      - if params[:tag]
        %div{class: "mt-8"}
          = render @solutions
      - else
        %div{class: "mt-4"}
          - if @solutions.today.any?
            %div{class: "w-full font-semibold text-xl mb-6 leading-none"}
              Today
            = render @solutions.today
            %div{class: "mt-8"}
          - if @solutions.past_week.any?
            %div{class: "w-full font-semibold text-xl mb-6 leading-none"}
              Past Week
            = render @solutions.past_week
            %div{class: "mt-8"}
          - if @solutions.past_month.any?
            %div{class: "w-full font-semibold text-xl mb-6 leading-none"}
              Past Month
            = render @solutions.past_month




    %div{class: "w-1/3 flex-shrink-0 flex flex-wrap"}
      %div{class: "w-full flex flex-col rounded-sm space-y-6"}
        %div{class: "py-3 px-4 bg-white border border-gray-400 rounded"}
          -# %div{class: "w-full"}
          -#   Create a new
          %div{class: "grid grid-cols-2 gap-2 "}
            = link_to "New Solution", new_solution_path,  class: "border-b-3 border-secondary px-0.5 pt-1 pb-0.5 mx-auto font-medium leading-4 transition-all hover:bg-secondary hover:text-white text-center tracking-wide"
            = link_to "New Request", new_request_path,  class: "border-b-3 border-secondary px-0.5 pt-1 pb-0.5 mx-auto font-medium leading-4 transition-all hover:bg-secondary hover:text-white text-center tracking-wide"
            -# %div{class: "cursor-pointer text-center rounded p-2 bg-gray-200 hover:bg-secondary hover:text-white"}
            -#   Request
            -# %div{class: "cursor-pointer text-center rounded p-2 bg-gray-200 hover:bg-secondary hover:text-white"}
            -#   Solution
        %div{class: " py-3 px-4 bg-white border border-gray-400 rounded"}
          %div{class: "w-full text-base font-medium"}
            Popular communities


          %div{class: "mt-3 text-sm space-y-1 flex flex-wrap"}
            - cache(:popular_communities, expires_in: 30.minutes) do
              - communities = Industry.order(Arel.sql('solutions_count + solution_votes_count DESC')).take(3) + Occupation.order(Arel.sql('solutions_count + solution_votes_count DESC')).take(3)
              - communities.each do |c|
                = link_to c, class: "-m-1.5 p-1.5" do
                  %div{class: "hover:bg-gray-200 -m-1.5 p-1.5"}
                    = "#{c.title} (#{c.class.to_s})"
                %div{class: "w-full"}

        %div{class: "pt-4 pb-4 px-4 bg-white border border-gray-400 rounded"}

          -# = "About #{niche_type}"

          %div{class: "#{cookies[:closeInfo] ? nil : 'hidden'}", "data-toggle-target": 'toggleable'}
            %div{class: "w-full text-base font-medium pb-2"}
              Hello! 👋
            Welcome to solved, a place to share and find the best new solutions to your problems.
            <br/><br/>
            🔍 Find your industry / occupation community and learn about better new solutions that could help you earn, or help you save time and money.
            %div{class: ""}
              <br/>
          ✨ Stay up to date by following your community to recieve a weekly email with the top solutions of the week.
          <br/><br/>
          ❤️ Help others in your community by posting about how you use the products you love to solve your problems.
          -# Find your industry / occupation community and learn about new solutions that could help you earn, or save you time and money.

          -# helps you find and stay up to date with the best new solutions to your problems.

          -# Subscribe to your industry / occupation community to stay up to date with the new ways
          -# Find your industry / occupation community to

          -# Welcome to solved, a place for problem solvers and product lovers to share

          -# Welcome to solved, a place for people to share how they use products they love to solve their problems.

          -# Welcome to solved, a place for people to help others find better solution

          -# Welcome to solved, a place for people to help others find better solutions by sharing how they use the products they love to solve their problems.
          -# a place for people to share how they use the %p

          -# a place for people to help others by sharing

          -# network effects
          -# we're solving a problem people already had and we were removing as much friction as %possible
          -# what are you a little too obsessed about? helping people find better solutions
          -# using the power of the community to create a great resource
          -# connecting problem solves and businesses all around the world

          -# is a palce for people to post how they use the proudcts they love to solve their problems
          -# Find you industry / occupation and learn about the best new solutions, tailored to your problems, that could save you time / money, or gerenate money.
          -# is a place to help others find better solutions by posting about how you use the proudct you love to solve your problems.

          -# to share how they solve their problem


          -# a place for you to help others find better solutions by sharing how you use the proudcts you love
          -# a place for other to help you find better solutions by sharing how they use the products they %lvoe

          -# a place for people to share how they use the products they love to solve their problems.

          -# a place for people to share the best new solutions to their problems.

          -# a place for people to share their solutions



          -# <br/><br/>
          -# Take part in your community by sharing how you solve your problems with the products you love, or by making a request for a solution to that dreadful task you do everyday.

        - if user_signed_in?
          - posts = current_user.following_by_type('Solution') + current_user.following_by_type('Request')
          - if posts.any?
            %div{class: " py-3 px-4 bg-white border border-gray-400 rounded"}
              %div{class: "w-full text-base font-medium"}
                Discussions you're following


              %div{class: "mt-3 text-sm space-y-1 flex flex-wrap"}
                - posts.each do |p|
                  = link_to p.title, p, class: "-m-1.5 p-1.5 hover:bg-gray-200"
                  %div{class: "w-full"}

app/views/search/index.html.haml
= render 'layouts/header'
= render 'niches/header'


This is the index action of the search controller