config/routes.rb
Rails.application.routes.draw do
  resources :mini_requests, only: :create
  resources :feedbacks, only: :create
  resources :lists
  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
  get "/robots.:format", to: "errors#robots"

  devise_for :users, controllers: { confirmations: 'confirmations', invitations: 'users/invitations', registrations: 'users/registrations', sessions: 'users/sessions' }

  authenticate :user, -> (user) { user.admin? } do
    mount PgHero::Engine, at: "pghero"
  end

  resources :after_signup, path: "/welcome"
  resources :suggested_keywords, only: [:create, :destroy]
  resources :suggested_communities, only: [:create, :destroy]

  resources :groups, only: [:show], path: "/l"

  root to: 'home#all'
  get '/search/solutions', to: 'search#solutions'

  get 'home', to: 'home#home'
  get 'recent', to: 'home#recent'
  # get 'requests', to: 'home#requests'
  # get 'requests/recent', to: 'home#requests_recent'
  get 'all', to: 'home#all'
  # get '/search/requests', to: 'search#requests'

  resources :industries, only: [], type: "Industry", path: "/i" do
    get "/", to: "solutions#niche_index"
    # get "/requests", to: "requests#niche_index"
    get "/search", to: "search#niche_index"
    member do
      get 'follow'
      get 'unfollow'
    end
  end

  resources :occupations, only: [], type: "Occupation", path: "/o" do
    get "/", to: "solutions#niche_index"
    # get "/requests", to: "requests#niche_index"
    get "/search", to: "search#niche_index"
    member do
      get 'follow'
      get 'unfollow'
    end
  end

  resources :products, only: [:index, :show]

  # Force www redirect
  # Start server with rails s -p 3000 -b lvh.me
  # Then go to http://www.lvh.me:3000
  # constraints(host: /^(?!www\.)/i) do
  #   get "controller#action" => redirect { |params, request|
  #     URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
  #   }
  # end

  post 'solutions/new', to: 'solutions#create'
  resources :solutions, except: [:index] do
    member do
      get 'follow'
      get 'unfollow'
      get 'upvote'
      get 'remove_upvote'
      resources :comments, except: :new do
        member do
          get 'upvote'
          get 'remove_upvote'
          delete 'really_destroy'
          post 'restore'
        end
      end
    end
  end

  post 'requests/new', to: 'requests#create'
  resources :requests do
    member do
      get 'upvote'
      get 'remove_upvote'
      get 'follow'
      get 'unfollow'
      resources :comments, except: :new do
        member do
          get 'upvote'
          get 'remove_upvote'
          delete 'really_destroy'
          post 'restore'
        end
      end
    end
  end
  resources :industry_categories, path: '/explore/i'
  resources :occupation_categories, path: '/explore/o'


end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id                   :bigint           not null, primary key
#  title                :text
#  description          :text
#  slug                 :text
#  keywords             :text
#  solutions_count      :integer          default(0), not null
#  solution_votes_count :integer          default(0), not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
class Group < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title

  has_many :group_solutions, dependent: :destroy
  has_many :solutions, through: :group_solutions

  has_many :suggested_keywords

  scope :popular,  -> { order(Arel.sql('solutions_count + solution_votes_count DESC')) }

  acts_as_followable

  def should_generate_new_friendly_id?
    title_changed? || super
  end

  def tags
    (self.solutions.tag_counts_on(:niche_specific_tags) + self.solutions.tag_counts_on(:general_tags)).uniq
  end

  def nb_followers
    Group.where("groups.id = #{self.id}").joins("JOIN follows ON followable_id = groups.id AND followable_type = '#{self.class.to_s}'").joins("JOIN users ON users.id = follower_id").where("users.confirmed_at IS NOT NULL").count
  end

  def keyword_list
    if self.keywords
      self.keywords.split("; ")
    else
      []
    end
  end

  def add_user_suggested_keyword(keyword)
    if self.keywords.blank?
      self.update(keywords: keyword)
    else
      self.update(keywords: "#{keywords}; #{keyword}")
    end
  end

  private

  def type
    "Group"
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  # def index
  #   @lists = List.all
  # end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  # def new
  #   @list = List.new
  # end

  # GET /lists/1/edit
  # def edit
  # end

  # POST /lists
  # POST /lists.json
  # def create
  #   @list = List.new(list_params)

  #   respond_to do |format|
  #     if @list.save
  #       format.html { redirect_to @list, notice: 'List was successfully created.' }
  #       format.json { render :show, status: :created, location: @list }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @list.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  # def update
  #   respond_to do |format|
  #     if @list.update(list_params)
  #       format.html { redirect_to @list, notice: 'List was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @list }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @list.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.fetch(:group, {})
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/groups/index.html.haml
%h1 Listing lists

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @lists.each do |list|
      %tr
        %td= link_to 'Show', list
        %td= link_to 'Edit', edit_list_path(list)
        %td= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New List', new_list_path

app/views/groups/new.html.haml
%h1 New list

= render 'form'

= link_to 'Back', lists_path

app/views/groups/show.html.haml
:javascript
  analytics.page("List - #{@group.title}");

- cache(@group) do
  %div{class: "mt-10 flex flex-wrap justify-center pb-20 px-4"}

    -# Logo, problem, product, and posted_to banner
    %div{class: "ml-6 flex flex-col w-full max-w-screen-lg"}
      -# %div{class: "flex-shrink-0"}
      -#   = image_tag @product.thumbnail_url, class: "object-cover w-28 h-28"
      %div{class: "text-xl"}
        The best new solutions for
      %div{class: "text-4xl font-semibold"}
        = @group.title

    %div{class: "mt-8 max-w-screen-lg w-full relative flex overflow-hidden"}
      %div{class: "w-2/3 flex flex-wrap"}
        %div{class: "flex justify-items-end"}
          -# %nav
            -# = link_to "Top", ""
        %div{class: "flex items-end"}
          %div{class: "text-xl md:text-2xl font-semibold text-right"}
            Top
          %div{class: "ml-2 leading-snug pl-2 border-l border-gray-600 text-gray-600 cursor-pointer text-sm md:text-base hover:underline"}
            = link_to 'Most recent', group_path(@group, sortBy: "recent")

        = render partial: 'solutions/niche_preview', as: :solution , collection: @group.solutions.includes(:user), cached: true

      -# %div{class: "w-1/3 flex-shrink-0 flex flex-wrap"}
        -# Test

  -# = link_to 'Edit', edit_product_path(@product)