config/routes.rb
Rails.application.routes.draw do
  resources :mini_requests, only: :create
  resources :feedbacks, only: :create
  resources :lists
  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
  get "/robots.:format", to: "errors#robots"

  devise_for :users, controllers: { confirmations: 'confirmations', invitations: 'users/invitations', registrations: 'users/registrations', sessions: 'users/sessions' }

  authenticate :user, -> (user) { user.admin? } do
    mount PgHero::Engine, at: "pghero"
  end

  resources :after_signup, path: "/welcome"
  resources :suggested_keywords, only: [:create, :destroy]
  resources :suggested_communities, only: [:create, :destroy]

  resources :groups, only: [:show], path: "/l"

  root to: 'home#all'
  get '/search/solutions', to: 'search#solutions'

  get 'home', to: 'home#home'
  get 'recent', to: 'home#recent'
  # get 'requests', to: 'home#requests'
  # get 'requests/recent', to: 'home#requests_recent'
  get 'all', to: 'home#all'
  # get '/search/requests', to: 'search#requests'

  resources :industries, only: [], type: "Industry", path: "/i" do
    get "/", to: "solutions#niche_index"
    # get "/requests", to: "requests#niche_index"
    get "/search", to: "search#niche_index"
    member do
      get 'follow'
      get 'unfollow'
    end
  end

  resources :occupations, only: [], type: "Occupation", path: "/o" do
    get "/", to: "solutions#niche_index"
    # get "/requests", to: "requests#niche_index"
    get "/search", to: "search#niche_index"
    member do
      get 'follow'
      get 'unfollow'
    end
  end

  resources :products, only: [:index, :show]

  # Force www redirect
  # Start server with rails s -p 3000 -b lvh.me
  # Then go to http://www.lvh.me:3000
  # constraints(host: /^(?!www\.)/i) do
  #   get "controller#action" => redirect { |params, request|
  #     URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
  #   }
  # end

  post 'solutions/new', to: 'solutions#create'
  resources :solutions, except: [:index] do
    member do
      get 'follow'
      get 'unfollow'
      get 'upvote'
      get 'remove_upvote'
      resources :comments, except: :new do
        member do
          get 'upvote'
          get 'remove_upvote'
          delete 'really_destroy'
          post 'restore'
        end
      end
    end
  end

  post 'requests/new', to: 'requests#create'
  resources :requests do
    member do
      get 'upvote'
      get 'remove_upvote'
      get 'follow'
      get 'unfollow'
      resources :comments, except: :new do
        member do
          get 'upvote'
          get 'remove_upvote'
          delete 'really_destroy'
          post 'restore'
        end
      end
    end
  end
  resources :industry_categories, path: '/explore/i'
  resources :occupation_categories, path: '/explore/o'


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :set_meta
  skip_after_action :verify_authorized
  before_action :authenticate_user!, except: [:niche_index, :all, :signed_out_home, :search_solutions]

  def all
    # if params[:tag]
    #   @posts = Solution.tagged_with(params[:tag], on: :general_tags).includes([:user, :product, :plan])
    # else
    @posts = Solution.front_page.all.top.includes([:product, :plan])
    # end
    set_meta_tags title: "solved: Find new and better solutions to your problems from people like you.",
                  description: "solved is a community of problem solvers and makers helping you find (or build!) better solutions to problems you face. Learn about new ways of doing things in your industry or occupation from people like you all around the world. Give back to the community by sharing your experience with products you love. Connect with budding entrepreneurs and give them feedback on their products to help them build better products for you.",
                  site: nil,
                  canonical: all_url
  end

  def home
    @posts = Solution.by_communities(current_user.niche_list).top.includes([:product, :plan])
    @is_solutions_page = true
    @is_top_results = true
    set_meta_tags title: "solved: Find new and better solutions to your problems from people like you.",
                  description: "solved is a community of problem solvers and makers helping you find (or build!) better solutions to problems you face. Learn about new ways of doing things in your industry or occupation from people like you all around the world. Give back to the community by sharing your experience with products you love. Connect with budding entrepreneurs and give them feedback on their products to help them build better products for you.",
                  site: nil,
                  canonical: home_url
  end


  def recent
    @posts = Solution.by_communities(current_user.niche_list).most_recent
    @is_solutions_page = true
    @is_top_results = false
    render 'home'
  end

  def requests
    @posts = Request.by_communities(current_user.niche_list).top
    @is_solutions_page = false
    @is_top_results = true
    render 'home'
  end

  def requests_recent
    @posts = Request.by_communities(current_user.niche_list).most_recent
    @is_solutions_page = false
    @is_top_results = false
    render 'home'
  end

  def search_solutions
    gon.index_name = 'solutions'
    render layout: false
  end

  private

  # def set_meta
  #   set_meta_tags title: "solved: Find new and better solutions to your problems from people like you.",
  #                 description: "solved is a community of problem solvers and makers helping you find (or build!) better solutions to problems you face. Learn about new ways of doing things in your industry or occupation from people like you all around the world. Give back to the community by sharing your experience with products you love. Connect with budding entrepreneurs and give them feedback on their products to help them build better products for you.",
  #                 site: nil
  #                 canonical: all_url
  # end

end

app/views/home/all.html.haml
:javascript
  analytics.page("All");

  function setCookie(cname, cvalue, exdays) {
    var d = new Date();
    d.setTime(d.getTime() + (exdays*24*60*60*1000));
    var expires = "expires="+ d.toUTCString();
    document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    console.log(cname + "=" + cvalue + ";" + expires + ";path=/");
  }

%div{class: "bg-white lg:w-1/2 lg:mx-auto rounded border border-gray-400 m-4 p-4 mb-8 #{cookies[:closeInfo1] ? 'hidden' : nil}", "data-toggle-target": 'toggleable', "data-controller": "toggle"}
  %div{class: "text-base flex items-center w-full justify-between font-medium"}
    Hello! 👋
    -# %div
    %div{class: "w-4 h-4  text-gray-600 hover:text-black cursor-pointer", "data-action": 'click->toggle#toggle touch->toggle#toggle', onclick: "document.cookie = setCookie('closeInfo1', true, 10);"}
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>

  %div{class: "py-1 w-full rounded-lg mt-1 text-base px-auto space-y-2"}

    %div{class: "text-sm"}
      Welcome to solved, a place to find out how others in your industry / occupation solve their problems.
      -# learn about better solutions from others in your industry / occupation. <br/>
    %div{class: "text-sm"}
      🔍 Use the search bar above to find your industry / occupation.
      -#  above and find out how others in your field are solving their problems.

      -# learn about new ways of solving problems from others in your field.
    %div{class: "text-sm"}
      👇 Alternatively, browse below to see popular solutions from all industries and occupations across solved.

%div{class: "w-full flex flex-col md:flex-row space-y-4 md:space-x-4 md:space-y-0 lg:space-x-0 justify-around my-8"}
  - cache(:popular_industries, expires_in: 30.minutes) do
    %div{class: "w-full lg:w-2/5 xl:w-1/3 text-sm bg-white pt-4 px-4 pb-3 rounded border border-gray-400"}
      %div{class: "font-semibold"}
        Popular Industries
      - communities = Industry.popular.take(3)
      - communities.each do |c|
        = link_to c, class: "popular-industry", data: { title: c.title, position: c.id } do
          %div{class: "hover:bg-gray-200 text-xssm rounded mt-1 p-1.5"}
            = "#{c.title}"
  - cache(:popular_occupations, expires_in: 30.minutes) do
    %div{class: "w-full lg:w-2/5 xl:w-1/3 text-sm bg-white pt-4 px-4 pb-3 rounded border border-gray-400"}
      %div{class: "font-semibold"}
        Popular Occupations
      - communities = Occupation.popular.take(3)
      - communities.each do |c|
        = link_to c, class: "popular-occupation", data: { title: c.title, position: c.id } do
          %div{class: "hover:bg-gray-200 text-xssm rounded mt-1 p-1.5"}
            = "#{c.title}"

%div{class: "mt-4 mb-10 px-4"}

  %div{class: "text-xl font-bold leading-tight"}
    Popular Solutions
  %div{class: "text-base font-medium tracking-wide text-gray-700 mb-6"}
    from all communities on solved

  - if @posts.today.exists?
    %div{class: "mt-8 w-full font-semibold text-lg leading-none"}
      Today
    %div{class: "mt-6 pb-6 border-b-2 border-gray-300 w-full grid grid-cols-2 gap-x-3 gap-y-6 md:grid-cols-3 lg:grid-cols-4"}
      = render @posts.today, cached: true

  - if @posts.past_week.exists?
    %div{class: "mt-8 w-full font-semibold text-lg leading-none"}
      Past Week
    %div{class: "mt-6 pb-6 border-b-2 border-gray-300 w-full grid grid-cols-2 gap-x-3 gap-y-6 md:grid-cols-3 lg:grid-cols-4"}
      = render @posts.past_week.take(12), cached: true
    -# %div{class: "flex items-center w-full"}
    -#   %div{class: "flex-1 relative"}
    -#     %div{class: "w-full absolute top-1/2 border-t-2 border-gray-300"}
    -#   %div{class: "flex-shrink-0 px-2 py-1 text-secondary font-medium mx-3 rounded-md flex items-center hover:bg-gray-200 cursor-pointer"}
    -#     Show more
    -#     %div{class: "ml-1"}
    -#       = svg_tag "chevron-down", class: "w-5 h-5"
    -#   %div{class: "flex-1 relative"}
    -#     %div{class: "w-full absolute top-1/2 border-t-2 border-gray-300"}

  -# - if @posts.past_month.exists?
  -# %div{class: "mt-8 w-full font-semibold text-lg leading-none"}
  -#   Past Month
  %div{class: "mt-6 w-full grid grid-cols-2 gap-x-3 gap-y-6 md:grid-cols-3 lg:grid-cols-4"}
    = render @posts.take(24), cached: true

app/views/home/home.html copy.haml
-# :javascript
-#   function setCookie(cname, cvalue, exdays) {
-#     var d = new Date();
-#     d.setTime(d.getTime() + (exdays*24*60*60*1000));
-#     var expires = "expires="+ d.toUTCString();
-#     document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
-#     console.log(cname + "=" + cvalue + ";" + expires + ";path=/");
-#   }

%div{class: "mt-10 flex justify-center pb-10"}
  %div{class: "max-w-screen-lg flex overflow-hidden", "data-controller": 'toggle'}
    %div{class: "w-full px-4 md:px-0 md:w-2/3 md:pr-12"}


      %div{class: "md:hidden py-3 px-4 mb-8 bg-white border border-gray-400 rounded"}
        %div{class: "w-full text-base font-medium"}
          My communities


        %div{class: "mt-3 text-sm space-y-1 flex flex-wrap"}
          - cache(current_user.niche_list) do
            - communities = current_user.niche_list
            - communities.each do |c|
              = link_to c, class: "-m-1.5 p-1.5" do
                %div{class: "hover:bg-gray-200 -m-1.5 p-1.5"}
                  = "#{c.title} (#{c.class.to_s})"
              %div{class: "w-full"}

      - active   = "text-secondary bg-gray-fb bg-opacity-50 px-2 py-2 font-medium rounded"
      - inactive = "text-gray-900 px-2 py-2 font-medium rounded hover:bg-gray-fb hover:bg-opacity-50"
      -# - active = "px-2 py-2 rounded bg-secondary text-white font-medium"
      -# - inactive = "px-2 py-2 rounded hover:bg-secondary hover:text-white font-medium text-gray-900"
      %div{class: "flex justify-between"}
        %div{class: "flex items-end"}
          %div{class: "text-xl md:text-2xl font-semibold"}
            - if @is_solutions_page
              Solutions
            - else
              Requests
          %div{class: "ml-2 leading-snug pl-2 border-l border-gray-600 text-gray-600 cursor-pointer text-sm md:text-base hover:underline"}
            - if @is_solutions_page
              - if @is_top_results
                = link_to 'Requests', requests_path
              - else
                = link_to 'Requests', requests_recent_path
            - else
              - if @is_top_results
                = link_to 'Solutions', home_path
              - else
                = link_to 'Solutions', recent_path

        %div{class: "flex items-end"}
          %div{class: "text-xl md:text-2xl font-semibold text-right"}
            - if @is_top_results
              Top
            - else
              Most recent
          %div{class: "ml-2 leading-snug pl-2 border-l border-gray-600 text-gray-600 cursor-pointer text-sm md:text-base hover:underline"}
            - if @is_top_results
              - if @is_solutions_page
                = link_to 'Most recent', recent_path
              - else
                = link_to 'Most recent', requests_recent_path
            - else
              -# Most results are showing
              - if @is_solutions_page
                = link_to 'Top', home_path
              - else
                = link_to 'Top', requests_path
      %div{class: "text-sm md:text-base"}
        (from the communities you follow)
      - if @is_solutions_page && !@posts.empty?
        %div{id: "expand-collapse", class: "text-gray-600 cursor-pointer text-sm hover:underline"}
          Expand

      - if @posts.empty?
        - if @is_solutions_page
          %div{class: "mt-20 w-full text-center text-xl font-medium"}
            No solutions from your communities yet 😔
          -# %div{class: "mt-8 w-full text-center text-lg px-36"}
          -#   Follow your industry / occupation community to see solutions here.
          %div{class: "mt-8 w-full text-center text-lg md:px-36"}
            = "Explore solutions from all industries and occupations #{link_to "here", all_path, class: "user-link pt-1"}.".html_safe
        - else
          %div{class: "mt-20 w-full text-center text-xl font-medium"}
            No requests from your communities yet 😔
          %div{class: "mt-8 w-full text-center text-lg md:px-36"}
            = "Explore solutions from all industries and occupations #{link_to "here", all_path, class: "user-link pt-1"}.".html_safe
      - else
        %div{class: "mt-8"}
          - if @posts.today.exists?
            %div{class: "w-full font-semibold text-xl mb-8 leading-none"}
              Today
            = render @posts.today
            %div{class: "mt-8"}
          - if @posts.past_week.exists?
            %div{class: "w-full font-semibold text-xl mb-8 leading-none"}
              Past Week
            = render @posts.past_week
            %div{class: "mt-8"}
          - if @posts.past_month.exists?
            %div{class: "w-full font-semibold text-xl mb-8 leading-none"}
              Past Month
            = render @posts.past_month




    %div{class: "hidden md:block w-1/3 flex-shrink-0 flex flex-wrap"}
      %div{class: "w-full flex flex-col rounded-sm space-y-6"}
        %div{class: "py-3 px-4 bg-white border border-gray-400 rounded"}
          -# %div{class: "w-full"}
          -#   Create a new
          %div{class: "grid grid-cols-2 gap-2 "}
            = link_to "New Solution", new_solution_path,  class: "border-b-3 border-secondary px-0.5 pt-1 pb-0.5 mx-auto font-medium leading-4 transition-all hover:bg-secondary hover:text-white text-center tracking-wide"
            = link_to "New Request", new_request_path,  class: "border-b-3 border-secondary px-0.5 pt-1 pb-0.5 mx-auto font-medium leading-4 transition-all hover:bg-secondary hover:text-white text-center tracking-wide"
            -# %div{class: "cursor-pointer text-center rounded p-2 bg-gray-200 hover:bg-secondary hover:text-white"}
            -#   Request
            -# %div{class: "cursor-pointer text-center rounded p-2 bg-gray-200 hover:bg-secondary hover:text-white"}
            -#   Solution
        %div{class: " py-3 px-4 bg-white border border-gray-400 rounded"}
          %div{class: "w-full text-base font-medium"}
            My communities


          %div{class: "mt-3 text-sm space-y-1 flex flex-wrap"}
            - cache(current_user.niche_list) do
              - communities = current_user.niche_list
              - communities.each do |c|
                = link_to c, class: "-m-1.5 p-1.5" do
                  %div{class: "hover:bg-gray-200 -m-1.5 p-1.5"}
                    = "#{c.title} (#{c.class.to_s})"
                %div{class: "w-full"}

        - if user_signed_in?
          - posts = current_user.following_by_type('Solution') + current_user.following_by_type('Request')
          - if posts.exists?
            %div{class: " py-3 px-4 bg-white border border-gray-400 rounded"}
              %div{class: "w-full text-base font-medium"}
                Discussion you're following


              %div{class: "mt-3 text-sm space-y-1 flex flex-wrap"}
                - posts.each do |p|
                  = link_to p.title, p, class: "-m-1.5 p-1.5 hover:bg-gray-200"
                  %div{class: "w-full"}

        -# %div{class: " py-3 px-4 bg-white border border-gray-400 rounded"}
        -#   %div{class: "w-full text-base font-medium"}
        -#     Popular communities


        -#   %div{class: "mt-3 text-sm space-y-1 flex flex-wrap"}
        -#     - cache(:popular_communities, expires_in: 30.minutes) do
        -#       - communities = Industry.is_postable.popular.take(3) + Occupation.is_postable.popular.take(3)
        -#       - communities.each do |c|
        -#         = link_to c, class: "-m-1.5 p-1.5" do
        -#           %div{class: "hover:bg-gray-200 -m-1.5 p-1.5"}
        -#             = "#{c.title} (#{c.class.to_s})"
        -#         %div{class: "w-full"}

        -# %div{class: "pt-4 pb-4 px-4 bg-white border border-gray-400 rounded"}

        -#   -# = "About #{niche_type}"


        -#   %div{class: "w-full text-base font-medium pb-2"}
        -#     Hello! 👋
        -#   Welcome to solved, a place to share and find the best new solutions to your problems.
        -#   <br/><br/>
        -#   🔍 Find your industry / occupation community and learn about better new solutions that could help you earn, or help you save time and money.
        -#   %div{class: ""}
        -#     <br/>
        -#   ✨ Stay up to date by following your community to recieve a weekly email with the top solutions of the week.
        -#   <br/><br/>
        -#   ❤️ Help others in your community by posting about how you solve your problems using the products you love.
        -# Find your industry / occupation community and learn about new solutions that could help you earn, or save you time and money.

        -# helps you find and stay up to date with the best new solutions to your problems.

        -# Subscribe to your industry / occupation community to stay up to date with the new ways
        -# Find your industry / occupation community to

        -# Welcome to solved, a place for problem solvers and product lovers to share

        -# Welcome to solved, a place for people to share how they use products they love to solve their problems.

        -# Welcome to solved, a place for people to help others find better solution

        -# Welcome to solved, a place for people to help others find better solutions by sharing how they use the products they love to solve their problems.
        -# a place for people to share how they use the %p

        -# a place for people to help others by sharing

        -# network effects
        -# we're solving a problem people already had and we were removing as much friction as %possible
        -# what are you a little too obsessed about? helping people find better solutions
        -# using the power of the community to create a great resource
        -# connecting problem solves and businesses all around the world

        -# is a palce for people to post how they use the proudcts they love to solve their problems
        -# Find you industry / occupation and learn about the best new solutions, tailored to your problems, that could save you time / money, or gerenate money.
        -# is a place to help others find better solutions by posting about how you use the proudct you love to solve your problems.

        -# to share how they solve their problem


        -# a place for you to help others find better solutions by sharing how you use the proudcts you love
        -# a place for other to help you find better solutions by sharing how they use the products they %lvoe

        -# a place for people to share how they use the products they love to solve their problems.

        -# a place for people to share the best new solutions to their problems.

        -# a place for people to share their solutions



        -# <br/><br/>
        -# Take part in your community by sharing how you solve your problems with the products you love, or by making a request for a solution to that dreadful task you do everyday.

app/views/home/home.html.haml
:javascript
  analytics.page("Home");

%div{class: "mt-4 mb-10 px-4"}
  %div{class: "text-xl font-bold leading-tight"}
    Solutions
  %div{class: "text-base font-medium tracking-wide text-gray-700 mb-6"}
    Trending solutions from the communities you follow

  - if @posts.today.exists?
    %div{class: "mt-8 w-full font-semibold text-lg leading-none"}
      Today
    %div{class: "mt-6 pb-6 border-b-2 border-gray-300 w-full grid grid-cols-2 gap-x-2 gap-y-6 md:grid-cols-3 lg:grid-cols-4"}
      = render @posts.today
  - if @posts.past_week.exists?
    %div{class: "mt-8 w-full font-semibold text-lg leading-none"}
      Past Week
    %div{class: "mt-6 pb-6 border-b-2 border-gray-300 w-full grid grid-cols-2 gap-x-2 gap-y-6 md:grid-cols-3 lg:grid-cols-4"}
      = render @posts.past_week

  - if @posts.past_month.exists?
    %div{class: "mt-8 w-full font-semibold text-lg leading-none"}
      Past Month
    %div{class: "mt-6 w-full grid grid-cols-2 gap-x-2 gap-y-6 md:grid-cols-3 lg:grid-cols-4"}
      = render @posts.past_month